### PR TITLE
I8 divide functions

### LINKED ISSUE #8: Divide util functions
For better organization, the functions in `utils.py` should be grouped into different files reflecting a single purpose.

### PR DESCRIPTION
**Pull request by eyvorchuk**
This PR solves [issue 8](https://github.com/pacificclimate/wps-tools/issues/8), which divides the functions from `utils.py` into separate modules for better organization. Some modules have also been renamed for clarity.

### CODE REVIEW

**Review by nikola-rados — CHANGES_REQUESTED** [review]
I think this is a good start, but we may have overdone the factoring out. I don't think there is anything wrong with having a general `utils` folder that holds most of this stuff. The only separation we really could use is with the hard coded inputs/outputs in an`io` folder and perhaps a `testing` folder. Otherwise things have been broken down a bit too much here. What are your thoughts @eyvorchuk?

**Comment by eyvorchuk** [comment]
>I think this is a good start, but we may have overdone the factoring out

I had mixed feelings on whether or not splitting the pywps i/o collection into two modules was too much, and I think having them in one is fine. If the `utils` folder has this (eg. `io_utils.py`) and `log_utils.py`, will that be fine? Or since `log_utils.py` only has one function right now, it should just go back into the same module as the i/o functions like originally?

>The only separation we really could use is with the hard coded inputs/outputs in an io folder and perhaps a testing folder.

This sounds good.

**Comment by nikola-rados** [comment]
I think we could stick with `io`, `utils` and `testing`. That pretty much covers everything we'll have available at the start. We can always break it apart more in the future if we need to.

**Review by nikola-rados — APPROVED** [review]
Looks good!

**Pull request merged**
